[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"
optimizer = true
runs = 200
bytecode_hash = "none"
via_ir = false
remappings = [
    "openzeppelin-contracts/=lib/openzeppelin-contracts/",
    "forge-std/=lib/openzeppelin-contracts/lib/forge-std/src/",
]

[fmt]
line_length = 100
tab_width = 4
int_types = "short"
number_underscore = "thousands"
